config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes/popular#index'

  resources :users, only: [:show, :edit, :update]
  resources :prototypes

  scope module: :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :popular, only: :index
    resources :newest, only: :index
    resources :tags, only: [:index, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :comments_count
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :prototype_thumbnails
  accepts_nested_attributes_for :prototype_thumbnails, reject_if: :reject_sub_images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_taggable
  acts_as_taggable_on :prototypes

  validates_presence_of :title, :catchcopy, :concept

  def reject_sub_images(attributes)
  attributes['image'].blank?
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/prototype_thumbnail.rb
class PrototypeThumbnail < ActiveRecord::Base
  belongs_to :prototype
  validates :image, :state, presence: true
  mount_uploader :image, ImageUploader
  enum state: { main: 0, sub: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  mount_uploader :image, UserImageUploader
  has_many :prototypes
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_out_path_for(resource)
      '/users/sign_in'
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image, :member, :profile, :work])
  end

end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController

  def create
    prototype = Prototype.find_by(params[:prototype_id])
    prototype.comments.create(comment_params)
    @comments = prototype.comments.includes(:user)
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :content)
  end
end

app/controllers/prototypes/likes_controller.rb
class Prototypes::LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_prototype, only: [:create, :destroy]

  def create
    @like = @prototype.likes.create(user_id: current_user.id)
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:format])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.order('created_at DESC').includes(:user).page(params[:page])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).order('likes_count DESC').page(params[:page]).per(8)
  end
end

app/controllers/prototypes/tags_controller.rb
class Prototypes::TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag).includes(:user, :prototype_thumbnails)
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index]
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    @comment = Comment.new(prototype_id: @prototype_id)
    @comments = @prototype.comments.includes(:user)
    @like  = @prototype.likes.find_by(user_id: current_user.id)
  end

  def new
    @prototype = Prototype.new
    @main_image = @prototype.prototype_thumbnails.build
    @sub_images = 3.times{ @prototype.prototype_thumbnails.build }
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to root_path, notice: 'Your post prototype successfuly.'
    else
      redirect_to new_prototype_path, alert: 'Your post prototype infomation is not enough'
    end
  end

  def edit
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to prototype_path, notice: 'Prototype was successfully updated.'
    else
      redirect_to edit_prototype_path, alert: 'Prototype was not successfully updated.'
    end
  end

  def destroy
    @prototype.destroy
    redirect_to root_path, notice: 'Prototype was successfully deleted.'
  end

  private

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catchcopy,
      :concept,
      prototype_thumbnails_attributes: [:id, :image, :state]
    ).merge(
      tag_list: params[:prototype][:tag]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user, only: [:show, :edit, :update]
before_action :authenticate_user!, only: [:edit, :update]

  def show
    @prototypes = @user.prototypes.page(params[:page]).per(8)
  end

  def edit
  end

  def update
    if @user.update(update_params)
      redirect_to root_path, notice: "Your edit successfuly."
    else
      redirect_to edit_user_path, alert: "Your edit infomation is not enough"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(
      :name,
      :image,
      :email,
      :member,
      :profile,
      :work
    )
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      //login
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{ "aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button" }
              = current_user.name
              %span.caret
            %ul.dropdown-menu{ role: "menu" }
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path(current_user)
          //not login
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/layouts/_messages.html.haml
-flash.each do |key, value|
  %div{ class: "alert alert- #{key}" }
    = link_to "x" ,"#", data: { dismiss: "alert" }, class: "close"
    %ul
      %ll
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render "layouts/messages"
    = yield
    = render "layouts/footer"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown.drop_menu_location
      %button.btn.btn-default{ id: "dropdownMenu", type: "button",  data: { toggle: "dropdown" } } ACTION
      %ul.dropdown-menu{ aria: {labelledby: "dropdownMenu1"} }
        %li
          =link_to "Delete", prototype_path(prototype), rel: "nofollow", data: {method: "delete"}
        %li
          =link_to "Edit", edit_prototype_path(prototype)
  .thumbnail#content
    - if prototype.prototype_thumbnails.main.present?
      = link_to prototype_path(prototype) do
        = image_tag(prototype.prototype_thumbnails.main.first.image)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.name}", user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime("%b %d")
      %ul.proto-tag-list.list-inline
        = render partial: "prototypes/tags/tag", collection: prototype.tags

app/views/prototypes/comments/_comment.html.haml
.media
  .media-left
    %img.media-object
    = link_to image_tag(comment.user.image,size: "64x64", alt: "64x64"), user_path(comment.user)
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
    %p
      = comment.content

app/views/prototypes/comments/create.js.haml
$("#comment_content").val("");
$("#js-comments").html(
"#{j( render @comments )}"
);

app/views/prototypes/edit.html.haml
.container.proto-new{ action: "" }
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload.js-image-preview
            = f.fields_for :prototype_thumbnails, @main_image do |thumbnail|
              = thumbnail.file_field :image
              = thumbnail.hidden_field :state, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            - 3.times do
              %li.list-group-item.col-md-4
                .image-upload.js-image-preview
                  = f.fields_for :prototype_thumbnails, @sub_images do |thumbnail|
                    = thumbnail.file_field :image
                    = thumbnail.hidden_field :state, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept"
      .row.text-center.proto-btn
        = f.submit value: "Publish", class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to like_path(like, prototype), method: :delete, id: "like-button", class: 'btn btn-default', remote: true do
      = image_tag("icon_heart_red.svg")
      LIKE
      %span.num
        = "#{ @prototype.likes.count }"
  - else
    = button_to likes_path(prototype), method: :post, class: 'btn btn-default', remote: true do
      = image_tag("icon_heart.svg")
      LIKE
      %span.num
        = "#{ @prototype.likes.count }"
- else
  = image_tag("icon_heart.svg")
  LIKE
  %span.num
    = "#{ @prototype.likes.count }"

app/views/prototypes/likes/create.js.haml
$("#like-buttons").html(
"#{j(render partial: 'prototypes/likes/like', locals: { prototype: @prototype, like: @like })}"
)

app/views/prototypes/likes/destroy.js.haml
$("#like-buttons").html(
"#{j(render partial: 'prototypes/likes/like', locals: { prototype: @prototype, like: @like })}"
);

app/views/prototypes/new.html.haml
.container.proto-new{ action: "" }
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload.js-image-preview
            = f.fields_for :prototype_thumbnails, @main_image do |thumbnail|
              = thumbnail.file_field :image
              = thumbnail.hidden_field :state, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            - 3.times do
              %li.list-group-item.col-md-4
                .image-upload.js-image-preview
                  = f.fields_for :prototype_thumbnails, @sub_images do |thumbnail|
                    = thumbnail.file_field :image
                    = thumbnail.hidden_field :state, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag 'prototype[tag][]', "", placeholder: "Web Design"
            .col-md-3
              = text_field_tag 'prototype[tag][]', "", placeholder: "UI"
            .col-md-3
              = text_field_tag 'prototype[tag][]', "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit value: "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ role: "presentation" }
          = link_to 'Popular PROTO', popular_index_path
        %li.active{ role: "presentation" }
          = link_to 'Newest PROTO', newest_index_path
      = button_tag 'View Tags', class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to 'Popular PROTO', popular_index_path
        %li{ role: "presentation" }
          = link_to 'Newest PROTO', newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to "#"
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by #{@prototype.user.name}", user_path(@prototype.user.id)
            %span.degree
            = @prototype.user.profile

    .col-md-6.text-right#like-buttons
      = render partial: "prototypes/likes/like", locals: { prototype: @prototype, like: @like }

  .row
    .col-md-9
      = image_tag(@prototype.prototype_thumbnails.main.first.image, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.prototype_thumbnails.sub.each do |sub|
          %li.list-group-item
            = image_tag sub.image, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
      = render partial: "prototypes/tags/tag", collection: @prototype.tags
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span#comments-count
      = "( #{ @prototype.comments.count } )"
      .col-md-8
        #js-comments
          = render partial: 'prototypes/comments/comment', collection: @comments
        .form-inline
          - if user_signed_in?
            = form_for [@comment], remote: true do |f|
              = f.hidden_field :user_id, value: current_user.id
              = f.hidden_field :prototype_id, value: @prototype.id
              %h4 Write a comment
              .row
                .form-group.col-md-10
                  = f.text_area :content, placeholder: "Your comments", class: "form-control", rows: "3"
                .form-group.col-md-2
                  = f.submit "Comment", class: 'button btn btn-primary'

app/views/prototypes/tags/_tag.html.haml
%li.col-md-4
  = link_to tag.name, tag_path(tag), class: "btn btn-default"

app/views/prototypes/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      = render partial: "prototypes/tags/tag", collection: @tags

app/views/prototypes/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to 'Popular PROTO', popular_index_path
        %li{ role: "presentation" }
          = link_to "Newest PROTO", newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

app/views/users/edit.html.haml
.container.user-new
  = form_for(@user) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Username"
            .user-image.col-md-2.js-image-preview{ style: "background-image: url(#{ current_user.image });" }
              %button.btn.btn-primary Change image
              = f.file_field :image
          .user-name.col-md-10
          = f.email_field :email, placeholder: "E-Mail"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: "30", rows: "4", placeholder: "Profile"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :work, cols: "30", rows: "4", placeholder: "Works"
      .row.text-center.user-btn
        = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag @user.image, class:"media-object", alt:"64x64", data: {holder:{rendered: true}}, data: {src: "holder.js/64x64"}, size: "64x64"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
          = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.work

      = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)